parse_notes:
  description: >
    Read the lesson notes provided via `notes` input. Produce a structured output containing:
    - short_summary: 5 bullet points that capture main ideas
    - key_vocabulary: list of key terms
    - learning_objectives: list of 3 measurable objectives
    Make sure output is concise and clearly labeled.
  expected_output: >
    short_summary: list
    key_vocabulary: list
    learning_objectives: list
  agent: note_reader

generate_lesson_plan:
  description: >
    Using the parsed notes (from `parse_notes`) and the topic, create a 45-minute lesson plan.
    The plan should include: opening (5 min), teaching segment (25 min), guided practice (10 min), closing (5 min), and optional homework.
  expected_output: >
    A lesson plan for a 45-minute class on {topic} with time estimates and activities, formatted clearly
  agent: lesson_planner

generate_quiz:
  description: >
    Create a short quiz (8-10 questions) based on parsed notes and the lesson plan. Include answers and a 1-line explanation for each answer. Mark difficulty for each.
  expected_output: >
    A list of 8-10 quiz questions with answers and difficulty labels to test knowledge on {topic}
  agent: quiz_maker

teaching_suggestions:
  description: >
    Provide 5 practical teaching tips and 3 interactive activities with materials list (if applicable). Include differentiation suggestions for students who struggle and enrichment ideas for advanced students.
  expected_output: >
    A list of 5 practical teaching tips, 3 interactive activities, and suggestions for differentiating instruction for {topic}
  agent: teaching_advisor